


EXTRACT_PREPOSITION_SENTENCES = True
MINIMAL_AMOUNT_OF_WORDS_IN_CLAUSE = 2


RUN_ANALYSER = True
ANALYZE_DATA_FROM_SCRATCH = RUN_ANALYSER and False
UPDATE_SHOWN_IMAGE = RUN_ANALYSER and False
SHOW_INTERACTIVE_IMAGE = RUN_ANALYSER and False

PRINT_LOGS = True
OUTPUT_REPRESENTATIVE_SENTENCES = True


CLEAN_TWEETS = False
CLEAN_MOVIE_LINES = False

DELIMITER = "###---###"
CHECKED_PREPOSITIONS = ["but", "although", "however", "even though"]