


EXTRACT_PREPOSITION_SENTENCES = False
RUN_ANALYSER = True
ANALYZE_DATA_FROM_SCRATCH = True
PRINT_LOGS = False
UPDATE_SHOWN_IMAGE = False

CLEAN_TWEETS = False
CLEAN_MOVIE_LINES = False

DELIMITER = "###---###"
CHECKED_PREPOSITIONS = ["but", "although", "however", "even though"]